server:
  port: 20001 #\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: api-gateway #\u6307\u5B9A\u670D\u52A1\u540D
eureka:
  client:
    registry-fetch-interval-seconds: 5 # \u83B7\u53D6\u670D\u52A1\u5217\u8868\u7684\u5468\u671F\uFF1A5s
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
zuul:
  prefix: /api # \u6DFB\u52A0\u8DEF\u7531\u524D\u7F00